name: test_case
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=2.3.0 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    get_it: ^4.0.4
    logger: ^0.9.2
    stacked: ^1.7.6
    stacked_services: ^0.5.4+2
    responsive_builder: ^0.2.0+2
    equatable: ^1.2.4
    google_fonts: ^2.2.0
    flutter_screenutil: ^5.3.1
    flutter_svg: ^1.0.2
    provider: ^4.3.3
    pin_code_fields: ^7.3.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^1.0.0
flutter:
    uses-material-design: true

    assets:
        - assets/icons/svg/
        - assets/images/jpeg/
        - lib/data/countries.json